//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelDragons.PixelBugs.Web.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PixelDragons.PixelBugs.Web.Resources.Controllers.CardController", typeof(CardController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Buttons_Save {
            get {
                return ResourceManager.GetString("Buttons_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field can only contain a number.
        /// </summary>
        internal static string Errors_NumbersOnly {
            get {
                return ResourceManager.GetString("Errors_NumbersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string Errors_RequiredField {
            get {
                return ResourceManager.GetString("Errors_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        internal static string Labels_Created {
            get {
                return ResourceManager.GetString("Labels_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned By:.
        /// </summary>
        internal static string Labels_OwnedBy {
            get {
                return ResourceManager.GetString("Labels_OwnedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points:.
        /// </summary>
        internal static string Labels_Points {
            get {
                return ResourceManager.GetString("Labels_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority:.
        /// </summary>
        internal static string Labels_Priority {
            get {
                return ResourceManager.GetString("Labels_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Labels_Status {
            get {
                return ResourceManager.GetString("Labels_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string Labels_Title {
            get {
                return ResourceManager.GetString("Labels_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string Labels_Type {
            get {
                return ResourceManager.GetString("Labels_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to card wall.
        /// </summary>
        internal static string Links_BackToCardWall {
            get {
                return ResourceManager.GetString("Links_BackToCardWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Links_Cancel {
            get {
                return ResourceManager.GetString("Links_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and go back to the card wall.
        /// </summary>
        internal static string Links_CancelBackToCardWall {
            get {
                return ResourceManager.GetString("Links_CancelBackToCardWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Card.
        /// </summary>
        internal static string Links_EditCard {
            get {
                return ResourceManager.GetString("Links_EditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Card.
        /// </summary>
        internal static string Links_NewCard {
            get {
                return ResourceManager.GetString("Links_NewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        internal static string Options_Anonymous {
            get {
                return ResourceManager.GetString("Options_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Owner.
        /// </summary>
        internal static string Options_NoOwner {
            get {
                return ResourceManager.GetString("Options_NoOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Wall.
        /// </summary>
        internal static string Titles_CardWall {
            get {
                return ResourceManager.GetString("Titles_CardWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Card.
        /// </summary>
        internal static string Titles_EditCard {
            get {
                return ResourceManager.GetString("Titles_EditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Card.
        /// </summary>
        internal static string Titles_NewCard {
            get {
                return ResourceManager.GetString("Titles_NewCard", resourceCulture);
            }
        }
    }
}
