//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelDragons.PixelBugs.Web.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IssueController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IssueController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PixelDragons.PixelBugs.Web.Resources.Controllers.IssueController", typeof(IssueController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Buttons_Save {
            get {
                return ResourceManager.GetString("Buttons_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Columns_Created {
            get {
                return ResourceManager.GetString("Columns_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Columns_Owner {
            get {
                return ResourceManager.GetString("Columns_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reported.
        /// </summary>
        internal static string Columns_Reported {
            get {
                return ResourceManager.GetString("Columns_Reported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Columns_Summary {
            get {
                return ResourceManager.GetString("Columns_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string Errors_RequiredField {
            get {
                return ResourceManager.GetString("Errors_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Labels_Description {
            get {
                return ResourceManager.GetString("Labels_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned By:.
        /// </summary>
        internal static string Labels_OwnedBy {
            get {
                return ResourceManager.GetString("Labels_OwnedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reported By:.
        /// </summary>
        internal static string Labels_ReportedBy {
            get {
                return ResourceManager.GetString("Labels_ReportedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary:.
        /// </summary>
        internal static string Labels_Summary {
            get {
                return ResourceManager.GetString("Labels_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Issue.
        /// </summary>
        internal static string Links_NewIssue {
            get {
                return ResourceManager.GetString("Links_NewIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        internal static string Options_Anonymous {
            get {
                return ResourceManager.GetString("Options_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Owner.
        /// </summary>
        internal static string Options_NoOwner {
            get {
                return ResourceManager.GetString("Options_NoOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues List.
        /// </summary>
        internal static string Titles_IssuesList {
            get {
                return ResourceManager.GetString("Titles_IssuesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Issue.
        /// </summary>
        internal static string Titles_NewIssue {
            get {
                return ResourceManager.GetString("Titles_NewIssue", resourceCulture);
            }
        }
    }
}
